[project]
name = "chair"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "bleak>=3.0.2",
    "platformio>=6.1.19",
    "pyserial>=3.5",
    "textual>=8.2.6",
]

[dependency-groups]
dev = [
    "pytest>=9.0.3",
]

[tool.pytest.ini_options]
pythonpath = ["src", "firmware/micropython"]
