#!/usr/bin/env python3
from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

import yaml


ROOT = Path(__file__).resolve().parents[1]
SPEC_PATH = ROOT / "spec" / "chair.yml"
SWIFT_PATH = ROOT / "ChairSniffer" / "ChairSniffer" / "Generated" / "ChairSpec.generated.swift"
COMMANDS_MD_PATH = ROOT / "docs" / "generated" / "commands.md"
LONG_MD_PATH = ROOT / "docs" / "generated" / "long_status_map.md"
SHORT_MD_PATH = ROOT / "docs" / "generated" / "short_status_map.md"
BLINK_MD_PATH = ROOT / "docs" / "generated" / "blink_indicators.md"
MASKS_MD_PATH = ROOT / "docs" / "generated" / "masks.md"

HEADER_SWIFT = """// Generated by tools/generate_chair_spec.py from spec/chair.yml.
// Do not edit by hand.

"""

HEADER_MD = "<!-- Generated by tools/generate_chair_spec.py from spec/chair.yml. Do not edit by hand. -->\n\n"


def load_spec() -> dict[str, Any]:
    with SPEC_PATH.open("r", encoding="utf-8") as f:
        return yaml.safe_load(f)


def swift_string(value: str) -> str:
    escaped = (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
    )
    return f'"{escaped}"'


def swift_note(value: str | None) -> str:
    return "nil" if value is None else swift_string(value)


def byte_expr(value: int | str) -> str:
    return "lastByteIndex" if value == "last" else str(value)


def bit_mask(bit: int) -> int:
    return 1 << bit


def bits_mask(bits: list[int]) -> int:
    high = max(bits)
    low = min(bits)
    return sum(1 << bit for bit in range(low, high + 1))


def bits_shift(bits: list[int]) -> int:
    return min(bits)


def command_rows(spec: dict[str, Any]) -> list[dict[str, Any]]:
    return spec["commands"] + spec["releases"] + spec["acks"]


def generate_swift(spec: dict[str, Any]) -> str:
    maps = spec["maps"]
    decode = spec["decode"]
    long_decode = decode["long"]
    short_decode = decode["short"]

    def dict_int_string(name: str, values: dict[Any, Any]) -> str:
        lines = [f"    static let {name}: [Int: String] = ["]
        for key, value in values.items():
            lines.append(f"        {int(key)}: {swift_string(str(value))},")
        lines.append("    ]")
        return "\n".join(lines)

    def dict_string_string(name: str, values: dict[Any, Any]) -> str:
        lines = [f"    static let {name}: [String: String] = ["]
        for key, value in values.items():
            lines.append(f"        {swift_string(str(key))}: {swift_string(str(value))},")
        lines.append("    ]")
        return "\n".join(lines)

    command_entries = ["    static let commandEntries: [String: CommandCatalog.Entry] = ["]
    for row in command_rows(spec):
        note = row.get("note") or row.get("hypothesis")
        command_entries.append(
            "        "
            f"{swift_string(row['code'])}: .init(name: {swift_string(row['name'])}, "
            f"role: .{row['role']}, note: {swift_note(note)}),"
        )
    command_entries.append("    ]")

    cheat = ["    static let commandCheatSheet: [(code: String, label: String)] = ["]
    for row in spec["commands"]:
        if "ui_label" in row:
            cheat.append(
                f"        (code: {swift_string(row['code'])}, label: {swift_string(row['ui_label'])}),"
            )
    cheat.append("    ]")

    auto_modes = ["    static let autoModeCodes: [String: String] = ["]
    for row in spec["commands"]:
        if "auto_mode" in row:
            auto_modes.append(f"        {swift_string(row['code'])}: {swift_string(row['auto_mode'])},")
    auto_modes.append("    ]")

    manual_bits = ["    static let manualTechniqueBits: [(name: String, byteIndex: Int, mask: UInt8)] = ["]
    for row in spec["blink_indicators"]["manual_techniques"]:
        manual_bits.append(
            f"        (name: {swift_string(row['name'])}, byteIndex: {row['byte']}, mask: 0x{bit_mask(row['bit']):02X}),"
        )
    manual_bits.append("    ]")

    air_bits = ["    static let airAreaBits: [(area: ChairAirArea, byteIndex: Int, mask: UInt8)] = ["]
    for row in spec["blink_indicators"]["air_areas"]:
        air_bits.append(
            f"        (area: .{row['id']}, byteIndex: {row['byte']}, mask: 0x{bit_mask(row['bit']):02X}),"
        )
    air_bits.append("    ]")

    roller_bits = ["    static let rollerPositionBits: [(position: ChairRollerPosition, byteIndex: Int, mask: UInt8)] = ["]
    for row in spec["blink_indicators"]["roller_positions"]:
        roller_bits.append(
            f"        (position: .{row['id']}, byteIndex: {row['byte']}, mask: 0x{bit_mask(row['bit']):02X}),"
        )
    roller_bits.append("    ]")

    long_masks = ", ".join(f"0x{row['mask']:02X}" for row in spec["known_masks"]["long"])
    short_masks = ", ".join(f"0x{row['mask']:02X}" for row in spec["known_masks"]["short"])

    manual_indicator = short_decode["manual_indicator"]

    constants = [
        f"    static let longKnownMask: [UInt8] = [{long_masks}]",
        f"    static let shortKnownMask: [UInt8] = [{short_masks}]",
        "",
        f"    static let manualIndicatorByteIndex = {manual_indicator['byte']}",
        f"    static let manualIndicatorMask: UInt8 = 0x{bit_mask(manual_indicator['bit']):02X}",
        "",
        f"    static let airByteIndex = {long_decode['air']['byte']}",
        f"    static let airMask: UInt8 = 0x{bit_mask(long_decode['air']['bit']):02X}",
        f"    static let airStrengthByteIndex = {long_decode['air_strength']['byte']}",
        f"    static let airStrengthMask: UInt8 = 0x{bits_mask(long_decode['air_strength']['bits']):02X}",
        f"    static let airStrengthShift = {bits_shift(long_decode['air_strength']['bits'])}",
        f"    static let speedByteIndex = {long_decode['speed']['byte']}",
        f"    static let speedMask: UInt8 = 0x{bits_mask(long_decode['speed']['bits']):02X}",
        f"    static let speedShift = {bits_shift(long_decode['speed']['bits'])}",
        f"    static let widthByteIndex = {long_decode['width']['byte']}",
        f"    static let widthMask: UInt8 = 0x{bits_mask(long_decode['width']['bits']):02X}",
        f"    static let widthShift = {bits_shift(long_decode['width']['bits'])}",
        f"    static let footRollerByteIndex = {long_decode['foot_roller']['byte']}",
        f"    static let footRollerMask: UInt8 = 0x{bit_mask(long_decode['foot_roller']['bit']):02X}",
        f"    static let heaterByteIndex = {byte_expr(long_decode['heater']['byte'])}",
        f"    static let heaterMask: UInt8 = 0x{bit_mask(long_decode['heater']['bit']):02X}",
        f"    static let motionActiveByteIndex = {long_decode['motion_active']['byte']}",
        f"    static let motionActiveMask: UInt8 = 0x{bit_mask(long_decode['motion_active']['bit']):02X}",
        f"    static let backRaiseByteIndex = {long_decode['back_raise']['byte']}",
        f"    static let backRaiseMask: UInt8 = 0x{bit_mask(long_decode['back_raise']['bit']):02X}",
        f"    static let backReclineByteIndex = {long_decode['back_recline']['byte']}",
        f"    static let backReclineMask: UInt8 = 0x{bit_mask(long_decode['back_recline']['bit']):02X}",
        f"    static let legRaiseByteIndex = {long_decode['leg_raise']['byte']}",
        f"    static let legRaiseMask: UInt8 = 0x{bit_mask(long_decode['leg_raise']['bit']):02X}",
        f"    static let legReclineByteIndex = {long_decode['leg_recline']['byte']}",
        f"    static let legReclineMask: UInt8 = 0x{bit_mask(long_decode['leg_recline']['bit']):02X}",
        f"    static let timerTensByteIndex = {long_decode['timer']['tens_byte']}",
        f"    static let timerOnesHighByteIndex = {long_decode['timer']['ones_high']['byte']}",
        f"    static let timerOnesHighMask: UInt8 = 0x{bits_mask(long_decode['timer']['ones_high']['bits']):02X}",
        f"    static let timerOnesHighShift = {bits_shift(long_decode['timer']['ones_high']['bits'])}",
        f"    static let timerOnesLowByteIndex = {long_decode['timer']['ones_low']['byte']}",
        f"    static let timerOnesLowMask: UInt8 = 0x{bits_mask(long_decode['timer']['ones_low']['bits']):02X}",
        f"    static let timerOnesLowShift = {bits_shift(long_decode['timer']['ones_low']['bits'])}",
        f"    static let areaByteIndex = {short_decode['area']['byte']}",
        f"    static let areaMask: UInt8 = 0x{bits_mask(short_decode['area']['bits']):02X}",
        f"    static let areaShift = {bits_shift(short_decode['area']['bits'])}",
    ]

    body = [
        "import Foundation",
        "",
        "enum ChairSpec {",
        "    static let lastByteIndex = -1",
        dict_string_string("sevenSegmentDigits", maps["seven_segment"]),
        "",
        dict_int_string("level135Values", maps["level_1_3_5"]),
        "",
        dict_int_string("widthValues", maps["width"]),
        "",
        dict_int_string("shortAreaValues", maps["short_area"]),
        "",
        "\n".join(command_entries),
        "",
        "\n".join(cheat),
        "",
        "\n".join(auto_modes),
        "",
        "\n".join(manual_bits),
        "",
        "\n".join(air_bits),
        "",
        "\n".join(roller_bits),
        "",
        "\n".join(constants),
        "}",
        "",
    ]
    return HEADER_SWIFT + "\n".join(body)


def md_escape(value: Any) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def md_table(headers: list[str], rows: list[list[Any]]) -> str:
    out = ["| " + " | ".join(headers) + " |"]
    out.append("| " + " | ".join("---" for _ in headers) + " |")
    for row in rows:
        out.append("| " + " | ".join(md_escape(cell) for cell in row) + " |")
    return "\n".join(out) + "\n"


def generate_commands_md(spec: dict[str, Any]) -> str:
    rows = []
    for row in command_rows(spec):
        rows.append([
            row["code"],
            row["name"],
            row["role"],
            row.get("release", ""),
            row.get("ui_label", ""),
            row.get("auto_mode", ""),
            row.get("note") or row.get("hypothesis", ""),
            row.get("confidence", ""),
        ])
    return HEADER_MD + "# Commands\n\n" + md_table(
        ["Code", "Name", "Role", "Release", "UI label", "Auto mode", "Note", "Confidence"],
        rows,
    )


def generate_status_map_md(spec: dict[str, Any], key: str, title: str) -> str:
    rows = [[row["range"], row["name"], row["rule"], row["confidence"]] for row in spec["status_maps"][key]]
    content = HEADER_MD + f"# {title}\n\n" + md_table(["Range", "Name", "Rule", "Confidence"], rows)
    if key == "short":
        content += "\n## Auto Mode Indicator Candidates\n\n"
        content += spec["decode"]["short"]["auto_mode_indicator"]["note"] + "\n\n"
        mode_rows = []
        for row in spec["decode"]["short"]["auto_mode_indicator"]["modes"]:
            if row.get("all_indicator_bits_zero"):
                bit = "all listed bits = 0"
                rule = "Only when short B3[b5] reports auto/non-manual"
            else:
                bit = f"B{row['byte']}[b{row['bit']}]"
                rule = f"active when bit == {row['active']}"
            mode_rows.append([row["display"], row["label"], bit, rule])
        content += md_table(["Display", "Label", "Bit", "Rule"], mode_rows)
    return content


def generate_blink_md(spec: dict[str, Any]) -> str:
    sections = [HEADER_MD + "# Blink Indicators\n"]
    manual_rows = [
        [row["name"], row.get("original_label", ""), f"B{row['byte']}[b{row['bit']}]", row.get("observed_motion", "")]
        for row in spec["blink_indicators"]["manual_techniques"]
    ]
    sections.append("\n## Manual Techniques\n\n")
    sections.append(md_table(["Name", "Original label", "Bit", "Observed motion"], manual_rows))

    air_rows = [
        [row["label"], row["id"], f"B{row['byte']}[b{row['bit']}]", "Default 0; blinks high; multiple bits may blink together"]
        for row in spec["blink_indicators"]["air_areas"]
    ]
    sections.append("\n## Air Areas\n\n")
    sections.append(md_table(["Label", "ID", "Bit", "Rule"], air_rows))

    roller_rows = [
        [row["label"], row["id"], f"B{row['byte']}[b{row['bit']}]", "Default 1; blinks low as the roller passes"]
        for row in spec["blink_indicators"]["roller_positions"]
    ]
    sections.append("\n## Roller Positions\n\n")
    sections.append(md_table(["Label", "ID", "Bit", "Rule"], roller_rows))
    return "".join(sections)


def generate_masks_md(spec: dict[str, Any]) -> str:
    sections = [HEADER_MD + "# Known Masks\n"]
    long_rows = [[f"B{row['byte']}", f"0x{row['mask']:02X}", row["note"]] for row in spec["known_masks"]["long"]]
    short_rows = [[f"B{row['byte']}", f"0x{row['mask']:02X}", row["note"]] for row in spec["known_masks"]["short"]]
    sections.append("\n## Long\n\n")
    sections.append(md_table(["Byte", "Mask", "Note"], long_rows))
    sections.append("\n## Short\n\n")
    sections.append(md_table(["Byte", "Mask", "Note"], short_rows))
    return "".join(sections)


def generated_files(spec: dict[str, Any]) -> dict[Path, str]:
    return {
        SWIFT_PATH: generate_swift(spec),
        COMMANDS_MD_PATH: generate_commands_md(spec),
        LONG_MD_PATH: generate_status_map_md(spec, "long", "Long Status Map"),
        SHORT_MD_PATH: generate_status_map_md(spec, "short", "Short Status Map"),
        BLINK_MD_PATH: generate_blink_md(spec),
        MASKS_MD_PATH: generate_masks_md(spec),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated files are stale")
    args = parser.parse_args()

    spec = load_spec()
    files = generated_files(spec)
    stale: list[Path] = []
    for path, content in files.items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                stale.append(path)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")

    if stale:
        for path in stale:
            print(f"stale: {path.relative_to(ROOT)}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
